# Generated by Django 3.2.12 on 2025-02-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
