# Generated by Django 5.1.6 on 2025-02-21 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
